steps:
  # Install backend dependencies and run tests
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        npm ci
        npm test
    id: 'backend-test'

  # Build frontend
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend
        npm ci
        npm run build
    id: 'frontend-build'

  # Upload backend to Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '-d'
      - '-x'
      - 'node_modules|coverage|.env'
      - 'backend'
      - 'gs://${_DEPLOYMENT_BUCKET}/backend/'
    id: 'upload-backend'
    waitFor: ['backend-test']

  # Upload frontend to Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '-d'
      - 'frontend/dist'
      - 'gs://${_DEPLOYMENT_BUCKET}/frontend/dist/'
    id: 'upload-frontend'
    waitFor: ['frontend-build']

  # Rolling update for backend MIG
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instance-groups'
      - 'managed'
      - 'rolling-action'
      - 'restart'
      - 'healthcard-backend-mig'
      - '--zone=us-central1-a'
    id: 'restart-backend'
    waitFor: ['upload-backend']

  # Rolling update for frontend MIG
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instance-groups'
      - 'managed'
      - 'rolling-action'
      - 'restart'
      - 'healthcard-frontend-mig'
      - '--zone=us-central1-a'
    id: 'restart-frontend'
    waitFor: ['upload-frontend']

substitutions:
  _DEPLOYMENT_BUCKET: 'healthcard-deployment-bucket-YOUR-PROJECT-ID'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
